# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.TextField()),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.News')),
            ],
        ),
    ]
