# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171001_0504'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField()),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.News')),
            ],
        ),
    ]
