# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20171001_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularity',
            name='_popularity',
            field=models.IntegerField(default=0),
        ),
    ]
