# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='created_at',
        ),
    ]
